site_name: Carina

theme:
  name: material
  palette:
    scheme: zebrunner
  logo: assets/logo.svg
  favicon: assets/favicon.svg
repo_url: https://github.com/zebrunner/carina
repo_name: carina

markdown_extensions:
  - attr_list
  - md_in_html

copyright: 2022 Zebrunner, Inc. All Rights Reserved
extra:
  homepage: https://zebrunner.com
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/zebrunner
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/company/zebrunner
    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/zebrunner
    - icon: fontawesome/brands/telegram 
      link: https://t.me/zebrunner

extra_css:
  - stylesheets/extra.css

nav:
    - Overview: index.md
    - Getting started: getting_started.md
    - Project structure: project_structure.md
    - Configuration: configuration.md
    - Execution: execution.md
    - Automation:
      - Web: automation/web.md
      - Mobile: automation/mobile.md
      - API: automation/api.md
      - Windows: automation/windows.md
    - Advanced:
      - Database: advanced/database.md
      - DataProvider: advanced/dataprovider.md
      - Driver: advanced/driver.md
      - Mobile: advanced/mobile.md
      - Localization: advanced/localization.md
      - Program flow: advanced/program_flow.md
      - Proxy: advanced/proxy.md
      - Screenshot: advanced/screenshot.md
      - Security: advanced/security.md
    - Integration:
      - Zebrunner: integration/zebrunner.md
    - Cucumber: cucumber.md
    - Contribution: contribution.md
    - Migration Guide (7.4.31 -> 1.0.0): migration.md
    - Migration Guide (1.1.5 -> 1.2.6): migration-1.1.5-1.2.6.md

